spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: order-service
    description: Payment orders
